import type { Category, TutorProfile, Review, Booking, User } from "@/types";

// Navigation Links
export const NAV_LINKS = {
  public: [
    { label: "Home", href: "/" },
    { label: "Find Tutors", href: "/tutors" },
    { label: "Categories", href: "/categories" },
    { label: "How It Works", href: "/#how-it-works" },
  ],
  student: [
    { label: "Dashboard", href: "/dashboard" },
    { label: "My Bookings", href: "/dashboard/bookings" },
    { label: "Profile", href: "/dashboard/profile" },
  ],
  tutor: [
    { label: "Dashboard", href: "/tutor/dashboard" },
    { label: "Availability", href: "/tutor/availability" },
    { label: "Profile", href: "/tutor/profile" },
  ],
  admin: [
    { label: "Dashboard", href: "/admin" },
    { label: "Users", href: "/admin/users" },
    { label: "Bookings", href: "/admin/bookings" },
    { label: "Categories", href: "/admin/categories" },
  ],
};

// Categories Mock Data
export const CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Mathematics",
    slug: "mathematics",
    description: "Algebra, Calculus, Statistics, and more",
    icon: "Calculator",
    tutorCount: 156,
  },
  {
    id: "2",
    name: "Science",
    slug: "science",
    description: "Physics, Chemistry, Biology",
    icon: "Atom",
    tutorCount: 124,
  },
  {
    id: "3",
    name: "Languages",
    slug: "languages",
    description: "English, Spanish, French, and more",
    icon: "Languages",
    tutorCount: 203,
  },
  {
    id: "4",
    name: "Programming",
    slug: "programming",
    description: "Web Development, Python, Java",
    icon: "Code",
    tutorCount: 189,
  },
  {
    id: "5",
    name: "Music",
    slug: "music",
    description: "Guitar, Piano, Vocals",
    icon: "Music",
    tutorCount: 87,
  },
  {
    id: "6",
    name: "Business",
    slug: "business",
    description: "Marketing, Finance, Management",
    icon: "Briefcase",
    tutorCount: 92,
  },
  {
    id: "7",
    name: "Arts & Design",
    slug: "arts-design",
    description: "Drawing, Graphic Design, Photography",
    icon: "Palette",
    tutorCount: 78,
  },
  {
    id: "8",
    name: "Test Prep",
    slug: "test-prep",
    description: "SAT, GRE, IELTS, TOEFL",
    icon: "GraduationCap",
    tutorCount: 145,
  },
];

// Mock Users
export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Dr. Ayesha Rahman",
    email: "ayesha@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1712 345678",
    createdAt: "2024-01-15",
    isActive: true,
  },
  {
    id: "u2",
    name: "Mohammad Karim",
    email: "karim@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1812 456789",
    createdAt: "2024-02-20",
    isActive: true,
  },
  {
    id: "u3",
    name: "Fatima Ahmed",
    email: "fatima@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1912 567890",
    createdAt: "2024-03-10",
    isActive: true,
  },
  {
    id: "u4",
    name: "Rafiq Hasan",
    email: "rafiq@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1612 678901",
    createdAt: "2024-01-25",
    isActive: true,
  },
  {
    id: "u5",
    name: "Nadia Islam",
    email: "nadia@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1512 789012",
    createdAt: "2024-04-05",
    isActive: true,
  },
  {
    id: "u6",
    name: "Tanvir Alam",
    email: "tanvir@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1412 890123",
    createdAt: "2024-04-12",
    isActive: true,
  },
  {
    id: "u7",
    name: "Dr. Sharmin Sultana",
    email: "sharmin@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1711 234567",
    createdAt: "2024-05-01",
    isActive: true,
  },
  {
    id: "u8",
    name: "Arif Mahmud",
    email: "arif@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1811 345678",
    createdAt: "2024-05-10",
    isActive: true,
  },
  {
    id: "u9",
    name: "Rumana Akter",
    email: "rumana@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1911 456789",
    createdAt: "2024-05-15",
    isActive: true,
  },
  {
    id: "u10",
    name: "Saiful Islam",
    email: "saiful@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1611 567890",
    createdAt: "2024-05-20",
    isActive: true,
  },
  {
    id: "u11",
    name: "Tahmina Rahman",
    email: "tahmina@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1511 678901",
    createdAt: "2024-05-25",
    isActive: true,
  },
  {
    id: "u12",
    name: "Jubayer Ahmed",
    email: "jubayer@skillbridge.com",
    role: "TUTOR",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1411 789012",
    createdAt: "2024-06-01",
    isActive: true,
  },
  {
    id: "u13",
    name: "Sadia Khan",
    email: "sadia@example.com",
    role: "STUDENT",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1312 901234",
    createdAt: "2024-06-05",
    isActive: true,
  },
  {
    id: "u14",
    name: "Imran Hossain",
    email: "imran@example.com",
    role: "STUDENT",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop&crop=face",
    phone: "+880 1212 012345",
    createdAt: "2024-06-10",
    isActive: true,
  },
];

// Mock Tutors
export const MOCK_TUTORS: TutorProfile[] = [
  {
    id: "t1",
    userId: "u1",
    user: MOCK_USERS[0],
    headline: "Mathematics Expert | University Lecturer | 12+ Years Experience",
    bio: "I am Dr. Ayesha Rahman, a passionate mathematics educator with over 12 years of teaching experience. Currently a senior lecturer at Dhaka University, I specialize in making complex mathematical concepts simple and engaging. My teaching approach focuses on building strong fundamentals while developing critical thinking and problem-solving skills. I have helped 500+ students achieve excellent results in board exams and university admissions.",
    hourlyRate: 800,
    experience: 12,
    education: "Ph.D. in Mathematics, University of Dhaka",
    subjects: ["Higher Mathematics", "Calculus", "Statistics", "Linear Algebra", "Discrete Math"],
    categories: [CATEGORIES[0]],
    languages: ["English", "Bengali"],
    rating: 4.9,
    totalReviews: 234,
    totalStudents: 512,
    totalSessions: 1847,
    isVerified: true,
    availability: [
      { id: "a1-1", tutorId: "t1", dayOfWeek: 0, startTime: "10:00", endTime: "12:00", isAvailable: true },
      { id: "a1-2", tutorId: "t1", dayOfWeek: 1, startTime: "09:00", endTime: "12:00", isAvailable: true },
      { id: "a1-3", tutorId: "t1", dayOfWeek: 1, startTime: "16:00", endTime: "20:00", isAvailable: true },
      { id: "a1-4", tutorId: "t1", dayOfWeek: 2, startTime: "09:00", endTime: "12:00", isAvailable: true },
      { id: "a1-5", tutorId: "t1", dayOfWeek: 3, startTime: "16:00", endTime: "20:00", isAvailable: true },
      { id: "a1-6", tutorId: "t1", dayOfWeek: 4, startTime: "09:00", endTime: "12:00", isAvailable: true },
      { id: "a1-7", tutorId: "t1", dayOfWeek: 5, startTime: "10:00", endTime: "14:00", isAvailable: true },
      { id: "a1-8", tutorId: "t1", dayOfWeek: 6, startTime: "10:00", endTime: "18:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-01-15",
  },
  {
    id: "t2",
    userId: "u2",
    user: MOCK_USERS[1],
    headline: "Senior Software Engineer | Full-Stack & Mobile Development",
    bio: "I'm Mohammad Karim, a senior software engineer with 9 years of industry experience working with top tech companies including Google and Samsung. I am passionate about teaching programming and helping students start their tech careers. My approach is practical and project-based - you'll build real applications while learning. Whether you're a complete beginner or looking to advance your skills, I can help you achieve your goals.",
    hourlyRate: 1200,
    experience: 9,
    education: "M.Sc. in Computer Science, BUET",
    subjects: ["JavaScript", "Python", "React", "Node.js", "Flutter", "Data Structures"],
    categories: [CATEGORIES[3]],
    languages: ["English", "Bengali"],
    rating: 4.8,
    totalReviews: 189,
    totalStudents: 324,
    totalSessions: 1156,
    isVerified: true,
    availability: [
      { id: "a2-1", tutorId: "t2", dayOfWeek: 1, startTime: "18:00", endTime: "22:00", isAvailable: true },
      { id: "a2-2", tutorId: "t2", dayOfWeek: 2, startTime: "18:00", endTime: "22:00", isAvailable: true },
      { id: "a2-3", tutorId: "t2", dayOfWeek: 3, startTime: "18:00", endTime: "22:00", isAvailable: true },
      { id: "a2-4", tutorId: "t2", dayOfWeek: 4, startTime: "18:00", endTime: "22:00", isAvailable: true },
      { id: "a2-5", tutorId: "t2", dayOfWeek: 5, startTime: "15:00", endTime: "22:00", isAvailable: true },
      { id: "a2-6", tutorId: "t2", dayOfWeek: 6, startTime: "10:00", endTime: "20:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-02-20",
  },
  {
    id: "t3",
    userId: "u3",
    user: MOCK_USERS[2],
    headline: "IELTS Expert | British Council Certified | Band 8.5 Achiever",
    bio: "Hello! I'm Fatima Ahmed, a certified English language instructor with extensive experience in IELTS and TOEFL preparation. I scored 8.5 in IELTS and have helped over 400 students achieve their target scores for university admissions abroad. My lessons focus on practical exam strategies, improving all four skills (Speaking, Writing, Reading, Listening), and building confidence. Join me to unlock your potential!",
    hourlyRate: 700,
    experience: 7,
    education: "M.A. in English Literature, Jahangirnagar University",
    subjects: ["IELTS Preparation", "TOEFL Preparation", "Spoken English", "Business English", "Academic Writing"],
    categories: [CATEGORIES[2], CATEGORIES[7]],
    languages: ["English", "Bengali", "Hindi"],
    rating: 4.9,
    totalReviews: 312,
    totalStudents: 456,
    totalSessions: 2134,
    isVerified: true,
    availability: [
      { id: "a3-1", tutorId: "t3", dayOfWeek: 0, startTime: "09:00", endTime: "13:00", isAvailable: true },
      { id: "a3-2", tutorId: "t3", dayOfWeek: 1, startTime: "08:00", endTime: "12:00", isAvailable: true },
      { id: "a3-3", tutorId: "t3", dayOfWeek: 2, startTime: "08:00", endTime: "12:00", isAvailable: true },
      { id: "a3-4", tutorId: "t3", dayOfWeek: 2, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a3-5", tutorId: "t3", dayOfWeek: 3, startTime: "08:00", endTime: "12:00", isAvailable: true },
      { id: "a3-6", tutorId: "t3", dayOfWeek: 4, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a3-7", tutorId: "t3", dayOfWeek: 5, startTime: "08:00", endTime: "14:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-03-10",
  },
  {
    id: "t4",
    userId: "u4",
    user: MOCK_USERS[3],
    headline: "Physics & Chemistry Specialist | Medical & Engineering Exam Prep",
    bio: "I'm Rafiq Hasan, a former research scientist with 8 years of teaching experience. I specialize in Physics and Chemistry for HSC, Medical, and Engineering admission test preparation. My students have secured positions in top medical colleges and engineering universities. I focus on conceptual clarity and problem-solving techniques that help students excel in competitive exams.",
    hourlyRate: 900,
    experience: 8,
    education: "M.Sc. in Physics, Rajshahi University",
    subjects: ["Physics", "Chemistry", "Medical Admission", "Engineering Admission", "HSC Science"],
    categories: [CATEGORIES[1]],
    languages: ["English", "Bengali"],
    rating: 4.7,
    totalReviews: 156,
    totalStudents: 287,
    totalSessions: 934,
    isVerified: true,
    availability: [
      { id: "a4-1", tutorId: "t4", dayOfWeek: 0, startTime: "16:00", endTime: "20:00", isAvailable: true },
      { id: "a4-2", tutorId: "t4", dayOfWeek: 1, startTime: "16:00", endTime: "21:00", isAvailable: true },
      { id: "a4-3", tutorId: "t4", dayOfWeek: 2, startTime: "16:00", endTime: "21:00", isAvailable: true },
      { id: "a4-4", tutorId: "t4", dayOfWeek: 3, startTime: "16:00", endTime: "21:00", isAvailable: true },
      { id: "a4-5", tutorId: "t4", dayOfWeek: 4, startTime: "16:00", endTime: "21:00", isAvailable: true },
      { id: "a4-6", tutorId: "t4", dayOfWeek: 5, startTime: "10:00", endTime: "20:00", isAvailable: true },
      { id: "a4-7", tutorId: "t4", dayOfWeek: 6, startTime: "10:00", endTime: "20:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-01-25",
  },
  {
    id: "t5",
    userId: "u5",
    user: MOCK_USERS[4],
    headline: "UI/UX Designer | Graphic Design Instructor | Adobe Certified",
    bio: "Hi, I'm Nadia Islam, a professional UI/UX designer and graphic design instructor with 6 years of industry experience. I've worked with international clients and top local agencies. I teach Adobe Photoshop, Illustrator, Figma, and complete UI/UX design workflows. Whether you want to build a career in design or improve your creative skills, I'll guide you step by step.",
    hourlyRate: 850,
    experience: 6,
    education: "B.F.A. in Graphic Design, Shanto-Mariam University",
    subjects: ["UI/UX Design", "Adobe Photoshop", "Adobe Illustrator", "Figma", "Logo Design"],
    categories: [CATEGORIES[6]],
    languages: ["English", "Bengali"],
    rating: 4.8,
    totalReviews: 98,
    totalStudents: 167,
    totalSessions: 534,
    isVerified: true,
    availability: [
      { id: "a5-1", tutorId: "t5", dayOfWeek: 0, startTime: "11:00", endTime: "17:00", isAvailable: true },
      { id: "a5-2", tutorId: "t5", dayOfWeek: 1, startTime: "19:00", endTime: "22:00", isAvailable: true },
      { id: "a5-3", tutorId: "t5", dayOfWeek: 2, startTime: "19:00", endTime: "22:00", isAvailable: true },
      { id: "a5-4", tutorId: "t5", dayOfWeek: 4, startTime: "19:00", endTime: "22:00", isAvailable: true },
      { id: "a5-5", tutorId: "t5", dayOfWeek: 5, startTime: "14:00", endTime: "20:00", isAvailable: true },
      { id: "a5-6", tutorId: "t5", dayOfWeek: 6, startTime: "11:00", endTime: "19:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-04-05",
  },
  {
    id: "t6",
    userId: "u6",
    user: MOCK_USERS[5],
    headline: "Business & Finance Expert | MBA | Startup Mentor",
    bio: "I'm Tanvir Alam, an MBA graduate with 10 years of experience in business consulting and finance. I have mentored 50+ startups and teach Business Administration, Accounting, Finance, and Marketing. My classes combine theoretical knowledge with real-world case studies. Perfect for BBA/MBA students and aspiring entrepreneurs looking to build a strong business foundation.",
    hourlyRate: 1000,
    experience: 10,
    education: "MBA in Finance, IBA, University of Dhaka",
    subjects: ["Business Administration", "Accounting", "Finance", "Marketing", "Entrepreneurship"],
    categories: [CATEGORIES[5]],
    languages: ["English", "Bengali"],
    rating: 4.6,
    totalReviews: 87,
    totalStudents: 143,
    totalSessions: 456,
    isVerified: true,
    availability: [
      { id: "a6-1", tutorId: "t6", dayOfWeek: 1, startTime: "20:00", endTime: "23:00", isAvailable: true },
      { id: "a6-2", tutorId: "t6", dayOfWeek: 2, startTime: "20:00", endTime: "23:00", isAvailable: true },
      { id: "a6-3", tutorId: "t6", dayOfWeek: 3, startTime: "20:00", endTime: "23:00", isAvailable: true },
      { id: "a6-4", tutorId: "t6", dayOfWeek: 5, startTime: "16:00", endTime: "22:00", isAvailable: true },
      { id: "a6-5", tutorId: "t6", dayOfWeek: 6, startTime: "10:00", endTime: "18:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-04-12",
  },
  {
    id: "t7",
    userId: "u7",
    user: MOCK_USERS[6],
    headline: "Biology & Medical Science Expert | MBBS | 15+ Years Teaching",
    bio: "I am Dr. Sharmin Sultana, an MBBS doctor and experienced biology teacher with over 15 years of teaching experience. I specialize in Biology for HSC, Medical admission preparation, and USMLE preparation. My deep understanding of medical sciences allows me to explain complex biological concepts in simple, memorable ways. I have helped 1000+ students get into medical colleges across Bangladesh. My teaching method includes visual aids, mnemonics, and real clinical examples.",
    hourlyRate: 950,
    experience: 15,
    education: "MBBS, Dhaka Medical College",
    subjects: ["Biology", "Zoology", "Botany", "Medical Admission", "Human Anatomy", "Physiology"],
    categories: [CATEGORIES[1]],
    languages: ["English", "Bengali"],
    rating: 4.9,
    totalReviews: 423,
    totalStudents: 876,
    totalSessions: 3245,
    isVerified: true,
    availability: [
      { id: "a7-1", tutorId: "t7", dayOfWeek: 0, startTime: "10:00", endTime: "14:00", isAvailable: true },
      { id: "a7-2", tutorId: "t7", dayOfWeek: 1, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a7-3", tutorId: "t7", dayOfWeek: 3, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a7-4", tutorId: "t7", dayOfWeek: 5, startTime: "10:00", endTime: "18:00", isAvailable: true },
      { id: "a7-5", tutorId: "t7", dayOfWeek: 6, startTime: "10:00", endTime: "18:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-05-01",
  },
  {
    id: "t8",
    userId: "u8",
    user: MOCK_USERS[7],
    headline: "Data Science & Machine Learning Expert | Google Certified",
    bio: "Hi, I'm Arif Mahmud, a senior data scientist with 7 years of experience working at tech giants. I hold Google Professional Data Engineer and TensorFlow certifications. I teach Python for Data Science, Machine Learning, Deep Learning, and Data Analysis. My courses are practical and project-based - you'll work on real datasets and build portfolio-worthy projects. I've trained 200+ professionals who now work at top companies including Google, Microsoft, and local tech firms.",
    hourlyRate: 1500,
    experience: 7,
    education: "M.Sc. in Data Science, North South University",
    subjects: ["Python", "Machine Learning", "Deep Learning", "Data Analysis", "SQL", "TensorFlow"],
    categories: [CATEGORIES[3]],
    languages: ["English", "Bengali"],
    rating: 4.8,
    totalReviews: 167,
    totalStudents: 234,
    totalSessions: 876,
    isVerified: true,
    availability: [
      { id: "a8-1", tutorId: "t8", dayOfWeek: 0, startTime: "14:00", endTime: "20:00", isAvailable: true },
      { id: "a8-2", tutorId: "t8", dayOfWeek: 2, startTime: "19:00", endTime: "23:00", isAvailable: true },
      { id: "a8-3", tutorId: "t8", dayOfWeek: 4, startTime: "19:00", endTime: "23:00", isAvailable: true },
      { id: "a8-4", tutorId: "t8", dayOfWeek: 5, startTime: "18:00", endTime: "23:00", isAvailable: true },
      { id: "a8-5", tutorId: "t8", dayOfWeek: 6, startTime: "10:00", endTime: "20:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-05-10",
  },
  {
    id: "t9",
    userId: "u9",
    user: MOCK_USERS[8],
    headline: "Arabic Language & Quran Teacher | Al-Azhar Graduate | Hafiza",
    bio: "Assalamu Alaikum! I'm Rumana Akter, a Hafiza and graduate of Al-Azhar University, Egypt. I have been teaching Arabic language and Quran for 10 years. I specialize in Quran recitation with Tajweed, Arabic grammar (Nahw & Sarf), and Islamic studies. My classes are suitable for all ages - from children learning their first Surahs to adults wanting to understand the Quran in its original language. I create a supportive, patient learning environment for everyone.",
    hourlyRate: 500,
    experience: 10,
    education: "Bachelor in Arabic & Islamic Studies, Al-Azhar University",
    subjects: ["Quran Recitation", "Tajweed", "Arabic Grammar", "Islamic Studies", "Hifz Program"],
    categories: [CATEGORIES[2]],
    languages: ["Arabic", "Bengali", "English"],
    rating: 5.0,
    totalReviews: 289,
    totalStudents: 534,
    totalSessions: 2456,
    isVerified: true,
    availability: [
      { id: "a9-1", tutorId: "t9", dayOfWeek: 0, startTime: "06:00", endTime: "09:00", isAvailable: true },
      { id: "a9-2", tutorId: "t9", dayOfWeek: 0, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a9-3", tutorId: "t9", dayOfWeek: 1, startTime: "06:00", endTime: "08:00", isAvailable: true },
      { id: "a9-4", tutorId: "t9", dayOfWeek: 2, startTime: "06:00", endTime: "08:00", isAvailable: true },
      { id: "a9-5", tutorId: "t9", dayOfWeek: 3, startTime: "06:00", endTime: "08:00", isAvailable: true },
      { id: "a9-6", tutorId: "t9", dayOfWeek: 4, startTime: "06:00", endTime: "08:00", isAvailable: true },
      { id: "a9-7", tutorId: "t9", dayOfWeek: 5, startTime: "06:00", endTime: "12:00", isAvailable: true },
      { id: "a9-8", tutorId: "t9", dayOfWeek: 6, startTime: "06:00", endTime: "12:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-05-15",
  },
  {
    id: "t10",
    userId: "u10",
    user: MOCK_USERS[9],
    headline: "Guitar & Music Theory Instructor | Berklee Online Certificate",
    bio: "Hey there! I'm Saiful Islam, a professional guitarist and music instructor with 8 years of teaching experience. I completed my certificate program from Berklee College of Music Online. I teach acoustic guitar, electric guitar, music theory, and songwriting. Whether you're a complete beginner wanting to play your first chords or an intermediate player looking to master advanced techniques, I'll create a personalized learning path for you. Let's make music together!",
    hourlyRate: 600,
    experience: 8,
    education: "Certificate in Guitar, Berklee College of Music Online",
    subjects: ["Acoustic Guitar", "Electric Guitar", "Music Theory", "Songwriting", "Fingerstyle"],
    categories: [CATEGORIES[4]],
    languages: ["English", "Bengali"],
    rating: 4.7,
    totalReviews: 134,
    totalStudents: 223,
    totalSessions: 756,
    isVerified: true,
    availability: [
      { id: "a10-1", tutorId: "t10", dayOfWeek: 0, startTime: "15:00", endTime: "21:00", isAvailable: true },
      { id: "a10-2", tutorId: "t10", dayOfWeek: 1, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a10-3", tutorId: "t10", dayOfWeek: 2, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a10-4", tutorId: "t10", dayOfWeek: 3, startTime: "17:00", endTime: "21:00", isAvailable: true },
      { id: "a10-5", tutorId: "t10", dayOfWeek: 5, startTime: "14:00", endTime: "22:00", isAvailable: true },
      { id: "a10-6", tutorId: "t10", dayOfWeek: 6, startTime: "14:00", endTime: "22:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-05-20",
  },
  {
    id: "t11",
    userId: "u11",
    user: MOCK_USERS[10],
    headline: "GRE & SAT Expert | 330+ GRE Score | Study Abroad Consultant",
    bio: "Hello! I'm Tahmina Rahman, a test prep specialist with a personal GRE score of 332 (170Q, 162V). I have 6 years of experience helping students achieve their target scores for studying abroad. I've guided 300+ students to top universities in the USA, Canada, and Europe. My teaching covers all sections - Verbal, Quantitative, and Analytical Writing - with proven strategies and extensive practice materials. I also provide guidance on university selection and application process.",
    hourlyRate: 1100,
    experience: 6,
    education: "M.S. in Applied Statistics, University of Michigan (USA)",
    subjects: ["GRE Preparation", "SAT Preparation", "GMAT Preparation", "Verbal Reasoning", "Quantitative Aptitude"],
    categories: [CATEGORIES[7]],
    languages: ["English", "Bengali"],
    rating: 4.9,
    totalReviews: 198,
    totalStudents: 312,
    totalSessions: 1234,
    isVerified: true,
    availability: [
      { id: "a11-1", tutorId: "t11", dayOfWeek: 0, startTime: "20:00", endTime: "23:00", isAvailable: true },
      { id: "a11-2", tutorId: "t11", dayOfWeek: 1, startTime: "20:00", endTime: "23:00", isAvailable: true },
      { id: "a11-3", tutorId: "t11", dayOfWeek: 2, startTime: "20:00", endTime: "23:00", isAvailable: true },
      { id: "a11-4", tutorId: "t11", dayOfWeek: 3, startTime: "20:00", endTime: "23:00", isAvailable: true },
      { id: "a11-5", tutorId: "t11", dayOfWeek: 5, startTime: "18:00", endTime: "23:00", isAvailable: true },
      { id: "a11-6", tutorId: "t11", dayOfWeek: 6, startTime: "10:00", endTime: "18:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-05-25",
  },
  {
    id: "t12",
    userId: "u12",
    user: MOCK_USERS[11],
    headline: "Digital Marketing Expert | Google & Meta Certified | Agency Owner",
    bio: "I'm Jubayer Ahmed, founder of a successful digital marketing agency and certified expert in Google Ads, Meta Ads, and SEO. With 5 years of hands-on experience managing campaigns worth millions of taka, I teach practical digital marketing skills that get results. My courses cover Social Media Marketing, Google Ads, Facebook/Instagram Ads, SEO, Content Marketing, and Email Marketing. Perfect for entrepreneurs, freelancers, and anyone looking to build a career in digital marketing.",
    hourlyRate: 900,
    experience: 5,
    education: "BBA in Marketing, BRAC University",
    subjects: ["Digital Marketing", "Google Ads", "Facebook Ads", "SEO", "Social Media Marketing", "Content Marketing"],
    categories: [CATEGORIES[5]],
    languages: ["English", "Bengali"],
    rating: 4.6,
    totalReviews: 112,
    totalStudents: 189,
    totalSessions: 567,
    isVerified: true,
    availability: [
      { id: "a12-1", tutorId: "t12", dayOfWeek: 0, startTime: "11:00", endTime: "17:00", isAvailable: true },
      { id: "a12-2", tutorId: "t12", dayOfWeek: 2, startTime: "19:00", endTime: "22:00", isAvailable: true },
      { id: "a12-3", tutorId: "t12", dayOfWeek: 4, startTime: "19:00", endTime: "22:00", isAvailable: true },
      { id: "a12-4", tutorId: "t12", dayOfWeek: 5, startTime: "15:00", endTime: "21:00", isAvailable: true },
      { id: "a12-5", tutorId: "t12", dayOfWeek: 6, startTime: "11:00", endTime: "19:00", isAvailable: true },
    ],
    reviews: [],
    createdAt: "2024-06-01",
  },
];

// Mock Reviews
export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    bookingId: "b1",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t1",
    rating: 5,
    comment: "Dr. Ayesha is an excellent teacher! She explained complex calculus concepts so clearly that I finally understood them. Her patience and dedication are remarkable. Highly recommend!",
    createdAt: "2024-12-15",
  },
  {
    id: "r2",
    bookingId: "b2",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t1",
    rating: 5,
    comment: "Best math tutor I've ever had. Her teaching method is unique and she makes sure you understand the fundamentals before moving forward.",
    createdAt: "2024-12-20",
  },
  {
    id: "r3",
    bookingId: "b3",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t2",
    rating: 5,
    comment: "Karim sir helped me understand React and Node.js in just a few sessions. His project-based approach is perfect for learning real-world development.",
    createdAt: "2024-12-18",
  },
  {
    id: "r4",
    bookingId: "b4",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t3",
    rating: 5,
    comment: "Fatima apa is amazing! I improved my IELTS score from 6.0 to 7.5 in just 2 months. Her tips and strategies are invaluable.",
    createdAt: "2024-12-22",
  },
  {
    id: "r5",
    bookingId: "b5",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t4",
    rating: 4,
    comment: "Rafiq sir explains physics concepts very well. His problem-solving techniques helped me a lot in my engineering admission prep.",
    createdAt: "2024-12-25",
  },
  {
    id: "r6",
    bookingId: "b6",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t5",
    rating: 5,
    comment: "Nadia apa taught me Figma and UI/UX design from scratch. Now I'm confident in designing professional interfaces. Excellent teaching!",
    createdAt: "2024-12-28",
  },
  {
    id: "r7",
    bookingId: "b7",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t7",
    rating: 5,
    comment: "Dr. Sharmin apa is the best biology teacher! Her explanations are so clear and she uses amazing visual aids. Got into medical college thanks to her!",
    createdAt: "2025-01-02",
  },
  {
    id: "r8",
    bookingId: "b8",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t8",
    rating: 5,
    comment: "Arif bhai's machine learning course is top-notch. Very practical approach with real projects. Landed a data science job after completing his course!",
    createdAt: "2025-01-05",
  },
  {
    id: "r9",
    bookingId: "b9",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t9",
    rating: 5,
    comment: "Rumana apa is an excellent Quran teacher. Her patience and teaching method helped me complete my Hifz. May Allah bless her.",
    createdAt: "2025-01-08",
  },
  {
    id: "r10",
    bookingId: "b10",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t11",
    rating: 5,
    comment: "Tahmina apa helped me score 325 on GRE! Her strategies for verbal and quant sections are brilliant. Highly recommended for anyone preparing for GRE.",
    createdAt: "2025-01-10",
  },
];

// Mock Bookings
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t1",
    tutor: MOCK_TUTORS[0],
    subject: "Higher Mathematics - Calculus",
    date: "2025-02-01",
    startTime: "10:00",
    endTime: "11:00",
    duration: 60,
    totalPrice: 800,
    status: "CONFIRMED",
    notes: "Need help with integration and differentiation",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    createdAt: "2025-01-28",
  },
  {
    id: "b2",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t2",
    tutor: MOCK_TUTORS[1],
    subject: "React.js & Node.js",
    date: "2025-02-02",
    startTime: "15:00",
    endTime: "16:00",
    duration: 60,
    totalPrice: 1200,
    status: "CONFIRMED",
    notes: "Building a full-stack MERN project",
    meetingLink: "https://meet.google.com/klm-nopq-rst",
    createdAt: "2025-01-28",
  },
  {
    id: "b3",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t3",
    tutor: MOCK_TUTORS[2],
    subject: "IELTS Speaking & Writing",
    date: "2025-01-28",
    startTime: "09:00",
    endTime: "10:00",
    duration: 60,
    totalPrice: 700,
    status: "COMPLETED",
    createdAt: "2025-01-20",
  },
  {
    id: "b4",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t4",
    tutor: MOCK_TUTORS[3],
    subject: "Physics - Engineering Admission",
    date: "2025-01-25",
    startTime: "16:00",
    endTime: "17:00",
    duration: 60,
    totalPrice: 900,
    status: "COMPLETED",
    createdAt: "2025-01-18",
  },
  {
    id: "b5",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t5",
    tutor: MOCK_TUTORS[4],
    subject: "UI/UX Design with Figma",
    date: "2025-02-03",
    startTime: "11:00",
    endTime: "12:00",
    duration: 60,
    totalPrice: 850,
    status: "CONFIRMED",
    notes: "Learning mobile app design",
    meetingLink: "https://meet.google.com/xyz-uvwx-stu",
    createdAt: "2025-01-29",
  },
  {
    id: "b6",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t6",
    tutor: MOCK_TUTORS[5],
    subject: "Business Finance",
    date: "2025-01-22",
    startTime: "14:00",
    endTime: "15:00",
    duration: 60,
    totalPrice: 1000,
    status: "CANCELLED",
    createdAt: "2025-01-15",
  },
  {
    id: "b7",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t7",
    tutor: MOCK_TUTORS[6],
    subject: "Biology - Medical Admission",
    date: "2025-02-04",
    startTime: "10:00",
    endTime: "11:00",
    duration: 60,
    totalPrice: 950,
    status: "CONFIRMED",
    notes: "Covering human physiology chapter",
    meetingLink: "https://meet.google.com/bio-med-prep",
    createdAt: "2025-01-29",
  },
  {
    id: "b8",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t8",
    tutor: MOCK_TUTORS[7],
    subject: "Machine Learning with Python",
    date: "2025-02-05",
    startTime: "18:00",
    endTime: "19:00",
    duration: 60,
    totalPrice: 1500,
    status: "CONFIRMED",
    notes: "Starting with supervised learning algorithms",
    meetingLink: "https://meet.google.com/ml-python-01",
    createdAt: "2025-01-29",
  },
  {
    id: "b9",
    studentId: "u13",
    student: MOCK_USERS[12],
    tutorId: "t9",
    tutor: MOCK_TUTORS[8],
    subject: "Quran Recitation with Tajweed",
    date: "2025-02-06",
    startTime: "07:00",
    endTime: "08:00",
    duration: 60,
    totalPrice: 500,
    status: "CONFIRMED",
    notes: "Learning Surah Al-Baqarah",
    meetingLink: "https://meet.google.com/quran-tajweed",
    createdAt: "2025-01-30",
  },
  {
    id: "b10",
    studentId: "u14",
    student: MOCK_USERS[13],
    tutorId: "t11",
    tutor: MOCK_TUTORS[10],
    subject: "GRE Verbal Preparation",
    date: "2025-02-07",
    startTime: "20:00",
    endTime: "21:00",
    duration: 60,
    totalPrice: 1100,
    status: "CONFIRMED",
    notes: "Focus on reading comprehension strategies",
    meetingLink: "https://meet.google.com/gre-verbal-prep",
    createdAt: "2025-01-30",
  },
];

// How It Works Steps
export const HOW_IT_WORKS = [
  {
    step: 1,
    title: "Find Your Tutor",
    description: "Browse our expert tutors by subject, rating, or price. Read reviews and find the perfect match.",
    icon: "Search",
  },
  {
    step: 2,
    title: "Book a Session",
    description: "Choose a convenient time slot from your tutor's availability and book instantly.",
    icon: "Calendar",
  },
  {
    step: 3,
    title: "Learn & Grow",
    description: "Connect with your tutor via video call and start learning. Track your progress along the way.",
    icon: "Video",
  },
  {
    step: 4,
    title: "Review & Repeat",
    description: "Rate your session and book again. Build a lasting learning relationship.",
    icon: "Star",
  },
];

// Stats for Landing Page
export const PLATFORM_STATS = [
  { label: "Expert Tutors", value: "500+", icon: "Users" },
  { label: "Happy Students", value: "10,000+", icon: "GraduationCap" },
  { label: "Sessions Completed", value: "50,000+", icon: "BookOpen" },
  { label: "Subjects Available", value: "100+", icon: "Lightbulb" },
];

// Testimonials
export const TESTIMONIALS = [
  {
    id: 1,
    name: "Rahul Ahmed",
    role: "Engineering Student, BUET",
    avatar: "https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=400&h=400&fit=crop&crop=face",
    content: "SkillBridge helped me excel in my engineering admission. Dr. Ayesha's math classes and Rafiq sir's physics sessions were game-changers. I got admitted to BUET!",
    rating: 5,
  },
  {
    id: 2,
    name: "Tasnim Akter",
    role: "Software Developer",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    content: "I learned full-stack development from Karim sir on SkillBridge. Within 4 months, I landed my first job as a junior developer. Best investment I've made!",
    rating: 5,
  },
  {
    id: 3,
    name: "Farhan Rahman",
    role: "Studying Abroad, UK",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    content: "Fatima apa helped me achieve IELTS 7.5 in just 2 months. Her tips for speaking and writing were incredible. Now I'm studying in the UK!",
    rating: 5,
  },
];

// Languages
export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Arabic",
  "Portuguese",
  "Hindi",
];

// Days of Week
export const DAYS_OF_WEEK = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

// Time Slots
export const TIME_SLOTS = [
  "08:00", "09:00", "10:00", "11:00", "12:00",
  "13:00", "14:00", "15:00", "16:00", "17:00",
  "18:00", "19:00", "20:00", "21:00",
];

// Price Ranges for Filter
export const PRICE_RANGES = [
  { label: "Under $25", min: 0, max: 25 },
  { label: "$25 - $50", min: 25, max: 50 },
  { label: "$50 - $75", min: 50, max: 75 },
  { label: "$75 - $100", min: 75, max: 100 },
  { label: "Over $100", min: 100, max: Infinity },
];

// Rating Options for Filter
export const RATING_OPTIONS = [
  { label: "4.5 & above", value: 4.5 },
  { label: "4.0 & above", value: 4.0 },
  { label: "3.5 & above", value: 3.5 },
  { label: "3.0 & above", value: 3.0 },
];
