import type { Category, TutorProfile, Review, Booking, User } from "@/types";

// Navigation Links
export const NAV_LINKS = {
  public: [
    { label: "Home", href: "/" },
    { label: "Find Tutors", href: "/tutors" },
    { label: "Categories", href: "/categories" },
    { label: "How It Works", href: "/#how-it-works" },
  ],
  student: [
    { label: "Dashboard", href: "/dashboard" },
    { label: "My Bookings", href: "/dashboard/bookings" },
    { label: "Profile", href: "/dashboard/profile" },
  ],
  tutor: [
    { label: "Dashboard", href: "/tutor/dashboard" },
    { label: "Availability", href: "/tutor/availability" },
    { label: "Profile", href: "/tutor/profile" },
  ],
  admin: [
    { label: "Dashboard", href: "/admin" },
    { label: "Users", href: "/admin/users" },
    { label: "Bookings", href: "/admin/bookings" },
    { label: "Categories", href: "/admin/categories" },
  ],
};

// Categories Mock Data
export const CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Mathematics",
    slug: "mathematics",
    description: "Algebra, Calculus, Statistics, and more",
    icon: "Calculator",
    tutorCount: 156,
  },
  {
    id: "2",
    name: "Science",
    slug: "science",
    description: "Physics, Chemistry, Biology",
    icon: "Atom",
    tutorCount: 124,
  },
  {
    id: "3",
    name: "Languages",
    slug: "languages",
    description: "English, Spanish, French, and more",
    icon: "Languages",
    tutorCount: 203,
  },
  {
    id: "4",
    name: "Programming",
    slug: "programming",
    description: "Web Development, Python, Java",
    icon: "Code",
    tutorCount: 189,
  },
  {
    id: "5",
    name: "Music",
    slug: "music",
    description: "Guitar, Piano, Vocals",
    icon: "Music",
    tutorCount: 87,
  },
  {
    id: "6",
    name: "Business",
    slug: "business",
    description: "Marketing, Finance, Management",
    icon: "Briefcase",
    tutorCount: 92,
  },
  {
    id: "7",
    name: "Arts & Design",
    slug: "arts-design",
    description: "Drawing, Graphic Design, Photography",
    icon: "Palette",
    tutorCount: 78,
  },
  {
    id: "8",
    name: "Test Prep",
    slug: "test-prep",
    description: "SAT, GRE, IELTS, TOEFL",
    icon: "GraduationCap",
    tutorCount: 145,
  },
];

// Mock Users
export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    role: "tutor",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    phone: "+1 234 567 8900",
    createdAt: "2024-01-15",
    isActive: true,
  },
  {
    id: "u2",
    name: "Michael Chen",
    email: "michael@example.com",
    role: "tutor",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    phone: "+1 234 567 8901",
    createdAt: "2024-02-20",
    isActive: true,
  },
  {
    id: "u3",
    name: "Emily Davis",
    email: "emily@example.com",
    role: "tutor",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
    phone: "+1 234 567 8902",
    createdAt: "2024-03-10",
    isActive: true,
  },
  {
    id: "u4",
    name: "David Wilson",
    email: "david@example.com",
    role: "tutor",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop",
    phone: "+1 234 567 8903",
    createdAt: "2024-01-25",
    isActive: true,
  },
  {
    id: "u5",
    name: "Jessica Martinez",
    email: "jessica@example.com",
    role: "student",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop",
    phone: "+1 234 567 8904",
    createdAt: "2024-04-05",
    isActive: true,
  },
  {
    id: "u6",
    name: "James Brown",
    email: "james@example.com",
    role: "student",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop",
    phone: "+1 234 567 8905",
    createdAt: "2024-04-12",
    isActive: true,
  },
];

// Mock Tutors
export const MOCK_TUTORS: TutorProfile[] = [
  {
    id: "t1",
    userId: "u1",
    user: MOCK_USERS[0],
    headline: "Expert Math Tutor | 10+ Years Experience",
    bio: "I'm a passionate mathematics educator with over 10 years of experience teaching students of all levels. I specialize in making complex concepts simple and engaging. My approach focuses on building strong foundations while developing problem-solving skills that last a lifetime.",
    hourlyRate: 45,
    experience: 10,
    education: "Ph.D. in Mathematics, MIT",
    subjects: ["Algebra", "Calculus", "Statistics", "Geometry"],
    categories: [CATEGORIES[0]],
    languages: ["English", "Spanish"],
    rating: 4.9,
    totalReviews: 128,
    totalStudents: 245,
    totalSessions: 892,
    isVerified: true,
    availability: [],
    reviews: [],
    createdAt: "2024-01-15",
  },
  {
    id: "t2",
    userId: "u2",
    user: MOCK_USERS[1],
    headline: "Full-Stack Developer & Programming Mentor",
    bio: "Senior software engineer with 8 years of industry experience at top tech companies. I love teaching programming and helping aspiring developers land their dream jobs. I focus on practical, project-based learning with real-world applications.",
    hourlyRate: 60,
    experience: 8,
    education: "M.S. in Computer Science, Stanford",
    subjects: ["JavaScript", "Python", "React", "Node.js", "Data Structures"],
    categories: [CATEGORIES[3]],
    languages: ["English", "Mandarin"],
    rating: 4.8,
    totalReviews: 95,
    totalStudents: 180,
    totalSessions: 654,
    isVerified: true,
    availability: [],
    reviews: [],
    createdAt: "2024-02-20",
  },
  {
    id: "t3",
    userId: "u3",
    user: MOCK_USERS[2],
    headline: "Native English Teacher | IELTS & TOEFL Expert",
    bio: "Certified English teacher with a passion for helping students achieve fluency. I've helped hundreds of students improve their English skills and ace standardized tests. My lessons are interactive, fun, and tailored to your specific goals.",
    hourlyRate: 35,
    experience: 6,
    education: "M.A. in Applied Linguistics, UCLA",
    subjects: ["English Grammar", "IELTS Prep", "TOEFL Prep", "Business English"],
    categories: [CATEGORIES[2], CATEGORIES[7]],
    languages: ["English", "French"],
    rating: 4.9,
    totalReviews: 156,
    totalStudents: 312,
    totalSessions: 1024,
    isVerified: true,
    availability: [],
    reviews: [],
    createdAt: "2024-03-10",
  },
  {
    id: "t4",
    userId: "u4",
    user: MOCK_USERS[3],
    headline: "Physics & Chemistry Specialist",
    bio: "Former research scientist turned educator. I bring real-world scientific experience into my teaching, making abstract concepts concrete and exciting. Perfect for high school and university students looking to excel in science.",
    hourlyRate: 50,
    experience: 7,
    education: "Ph.D. in Physics, Caltech",
    subjects: ["Physics", "Chemistry", "AP Physics", "AP Chemistry"],
    categories: [CATEGORIES[1]],
    languages: ["English"],
    rating: 4.7,
    totalReviews: 72,
    totalStudents: 145,
    totalSessions: 489,
    isVerified: true,
    availability: [],
    reviews: [],
    createdAt: "2024-01-25",
  },
];

// Mock Reviews
export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    bookingId: "b1",
    studentId: "u5",
    student: MOCK_USERS[4],
    tutorId: "t1",
    rating: 5,
    comment: "Sarah is an amazing tutor! She explained calculus concepts in a way I finally understood. Highly recommend!",
    createdAt: "2024-12-15",
  },
  {
    id: "r2",
    bookingId: "b2",
    studentId: "u6",
    student: MOCK_USERS[5],
    tutorId: "t1",
    rating: 5,
    comment: "Best math tutor I've ever had. Patient, knowledgeable, and makes learning fun.",
    createdAt: "2024-12-20",
  },
  {
    id: "r3",
    bookingId: "b3",
    studentId: "u5",
    student: MOCK_USERS[4],
    tutorId: "t2",
    rating: 5,
    comment: "Michael helped me understand React hooks in just one session. His teaching style is perfect for beginners.",
    createdAt: "2024-12-18",
  },
  {
    id: "r4",
    bookingId: "b4",
    studentId: "u6",
    student: MOCK_USERS[5],
    tutorId: "t3",
    rating: 4,
    comment: "Emily is very patient and her IELTS tips were super helpful. Improved my score by 1.5 bands!",
    createdAt: "2024-12-22",
  },
];

// Mock Bookings
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "b1",
    studentId: "u5",
    student: MOCK_USERS[4],
    tutorId: "t1",
    tutor: MOCK_TUTORS[0],
    subject: "Calculus",
    date: "2025-01-30",
    startTime: "10:00",
    endTime: "11:00",
    duration: 60,
    totalPrice: 45,
    status: "confirmed",
    notes: "Need help with integration techniques",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    createdAt: "2025-01-25",
  },
  {
    id: "b2",
    studentId: "u5",
    student: MOCK_USERS[4],
    tutorId: "t2",
    tutor: MOCK_TUTORS[1],
    subject: "React.js",
    date: "2025-01-31",
    startTime: "14:00",
    endTime: "15:00",
    duration: 60,
    totalPrice: 60,
    status: "confirmed",
    notes: "Want to learn about state management",
    meetingLink: "https://meet.google.com/klm-nopq-rst",
    createdAt: "2025-01-26",
  },
  {
    id: "b3",
    studentId: "u6",
    student: MOCK_USERS[5],
    tutorId: "t3",
    tutor: MOCK_TUTORS[2],
    subject: "IELTS Speaking",
    date: "2025-01-28",
    startTime: "09:00",
    endTime: "10:00",
    duration: 60,
    totalPrice: 35,
    status: "completed",
    createdAt: "2025-01-20",
  },
  {
    id: "b4",
    studentId: "u5",
    student: MOCK_USERS[4],
    tutorId: "t4",
    tutor: MOCK_TUTORS[3],
    subject: "AP Physics",
    date: "2025-01-25",
    startTime: "16:00",
    endTime: "17:00",
    duration: 60,
    totalPrice: 50,
    status: "completed",
    createdAt: "2025-01-18",
  },
  {
    id: "b5",
    studentId: "u6",
    student: MOCK_USERS[5],
    tutorId: "t1",
    tutor: MOCK_TUTORS[0],
    subject: "Statistics",
    date: "2025-01-22",
    startTime: "11:00",
    endTime: "12:00",
    duration: 60,
    totalPrice: 45,
    status: "cancelled",
    createdAt: "2025-01-15",
  },
];

// How It Works Steps
export const HOW_IT_WORKS = [
  {
    step: 1,
    title: "Find Your Tutor",
    description: "Browse our expert tutors by subject, rating, or price. Read reviews and find the perfect match.",
    icon: "Search",
  },
  {
    step: 2,
    title: "Book a Session",
    description: "Choose a convenient time slot from your tutor's availability and book instantly.",
    icon: "Calendar",
  },
  {
    step: 3,
    title: "Learn & Grow",
    description: "Connect with your tutor via video call and start learning. Track your progress along the way.",
    icon: "Video",
  },
  {
    step: 4,
    title: "Review & Repeat",
    description: "Rate your session and book again. Build a lasting learning relationship.",
    icon: "Star",
  },
];

// Stats for Landing Page
export const PLATFORM_STATS = [
  { label: "Expert Tutors", value: "500+", icon: "Users" },
  { label: "Happy Students", value: "10,000+", icon: "GraduationCap" },
  { label: "Sessions Completed", value: "50,000+", icon: "BookOpen" },
  { label: "Subjects Available", value: "100+", icon: "Lightbulb" },
];

// Testimonials
export const TESTIMONIALS = [
  {
    id: 1,
    name: "Alex Thompson",
    role: "University Student",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop",
    content: "EduBridge helped me go from struggling in calculus to getting an A. My tutor Sarah made complex concepts so easy to understand!",
    rating: 5,
  },
  {
    id: 2,
    name: "Maria Garcia",
    role: "Working Professional",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop",
    content: "I needed to learn Python for my new job. Michael was incredible - in just 2 months, I was coding confidently at work.",
    rating: 5,
  },
  {
    id: 3,
    name: "Ryan Kim",
    role: "High School Student",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop",
    content: "Thanks to Emily, I improved my IELTS score from 6.0 to 7.5! Her test strategies were exactly what I needed.",
    rating: 5,
  },
];

// Languages
export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Arabic",
  "Portuguese",
  "Hindi",
];

// Days of Week
export const DAYS_OF_WEEK = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

// Time Slots
export const TIME_SLOTS = [
  "08:00", "09:00", "10:00", "11:00", "12:00",
  "13:00", "14:00", "15:00", "16:00", "17:00",
  "18:00", "19:00", "20:00", "21:00",
];

// Price Ranges for Filter
export const PRICE_RANGES = [
  { label: "Under $25", min: 0, max: 25 },
  { label: "$25 - $50", min: 25, max: 50 },
  { label: "$50 - $75", min: 50, max: 75 },
  { label: "$75 - $100", min: 75, max: 100 },
  { label: "Over $100", min: 100, max: Infinity },
];

// Rating Options for Filter
export const RATING_OPTIONS = [
  { label: "4.5 & above", value: 4.5 },
  { label: "4.0 & above", value: 4.0 },
  { label: "3.5 & above", value: 3.5 },
  { label: "3.0 & above", value: 3.0 },
];
